# Generated by Django 2.2.5 on 2019-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
