# Generated by Django 2.2.5 on 2019-10-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 20, 11, 28, 713971))),
                ('guests', models.IntegerField(blank=True)),
            ],
        ),
    ]
